import type { FingerprintRule } from '@sasp/shared';

type Seed = Omit<FingerprintRule, 'id' | 'enabled' | 'source'>;

export const databaseRules: Seed[] = [
  {
    name: 'MySQL Banner',
    product: 'MySQL',
    category: 'database',
    priority: 0,
    matchers: [
      { type: 'banner', pattern: '\\x00\\x00\\x00\\x0a([\\d.]+)', versionGroup: 1 },
      { type: 'banner', pattern: 'mysql_native_password' },
      { type: 'banner', pattern: 'caching_sha2_password' },
    ],
    matchMode: 'any',
    tags: ['database', 'mysql'],
  },
  {
    name: 'MariaDB Banner',
    product: 'MariaDB',
    category: 'database',
    priority: 0,
    matchers: [
      { type: 'banner', pattern: '([\\d.]+)-MariaDB', versionGroup: 1 },
      { type: 'banner', pattern: 'MariaDB' },
    ],
    matchMode: 'any',
    tags: ['database', 'mariadb'],
  },
  {
    name: 'Redis Protocol',
    product: 'Redis',
    category: 'database',
    priority: 2,
    matchers: [
      { type: 'banner', pattern: '-NOAUTH Authentication required' },
      { type: 'banner', pattern: '-DENIED Redis is running in protected mode' },
      { type: 'banner', pattern: '\\+PONG' },
      { type: 'banner', pattern: '# Server\\r\\nredis_version:([\\d.]+)', versionGroup: 1 },
      { type: 'banner', pattern: 'redis_version' },
    ],
    matchMode: 'any',
    tags: ['database', 'redis', 'kv'],
  },
  {
    name: 'PostgreSQL Protocol',
    product: 'PostgreSQL',
    category: 'database',
    priority: 2,
    matchers: [
      { type: 'banner', pattern: 'FATAL.*password authentication' },
      { type: 'banner', pattern: 'no pg_hba\\.conf entry' },
      { type: 'banner', pattern: 'SCRAM-SHA-256' },
    ],
    matchMode: 'any',
    tags: ['database', 'postgres'],
  },
  {
    name: 'PolarDB (MySQL)',
    product: 'PolarDB',
    category: 'database',
    priority: 2,
    matchers: [
      { type: 'banner', pattern: 'PolarDB' },
      { type: 'header', field: 'server', pattern: 'PolarDB' },
    ],
    matchMode: 'any',
    tags: ['database', 'mysql', 'aliyun'],
  },
  {
    name: 'ADB (AnalyticDB)',
    product: 'ADB',
    category: 'database',
    priority: 2,
    matchers: [
      { type: 'banner', pattern: 'AnalyticDB' },
      { type: 'banner', pattern: 'AliSQL' },
    ],
    matchMode: 'any',
    tags: ['database', 'mysql', 'aliyun', 'olap'],
  },
  {
    name: 'StarRocks',
    product: 'StarRocks',
    category: 'database',
    priority: 2,
    matchers: [
      { type: 'banner', pattern: 'StarRocks' },
      { type: 'body', pattern: 'StarRocks' },
      { type: 'title', pattern: 'StarRocks' },
    ],
    matchMode: 'any',
    tags: ['database', 'mysql', 'olap'],
  },
  {
    name: 'TiDB',
    product: 'TiDB',
    category: 'database',
    priority: 2,
    matchers: [
      { type: 'banner', pattern: 'TiDB' },
      { type: 'body', pattern: 'TiDB' },
      { type: 'title', pattern: 'TiDB' },
    ],
    matchMode: 'any',
    tags: ['database', 'mysql', 'tidb', 'distributed-sql'],
  },
  {
    name: 'OceanBase',
    product: 'OceanBase',
    category: 'database',
    priority: 2,
    matchers: [
      { type: 'banner', pattern: 'OceanBase|OBServer|OBProxy' },
      { type: 'body', pattern: 'OceanBase|OBServer|OBProxy' },
      { type: 'title', pattern: 'OceanBase|OBProxy' },
    ],
    matchMode: 'any',
    tags: ['database', 'mysql', 'oceanbase', 'distributed-sql'],
  },
  {
    name: 'Apache Doris',
    product: 'Doris',
    category: 'database',
    priority: 2,
    matchers: [
      { type: 'banner', pattern: 'Doris|Apache Doris' },
      { type: 'body', pattern: 'Doris FE|Apache Doris|Doris Manager' },
      { type: 'title', pattern: 'Doris|Doris FE' },
    ],
    matchMode: 'any',
    tags: ['database', 'mysql', 'doris', 'olap'],
  },
  {
    name: 'MongoDB Protocol',
    product: 'MongoDB',
    category: 'database',
    priority: 2,
    matchers: [
      { type: 'banner', pattern: 'It looks like you are trying to access MongoDB' },
      { type: 'body', pattern: 'It looks like you are trying to access MongoDB' },
      { type: 'banner', pattern: 'MongoDB' },
    ],
    matchMode: 'any',
    tags: ['database', 'mongodb', 'nosql'],
  },
  {
    name: 'Elasticsearch',
    product: 'Elasticsearch',
    category: 'database',
    priority: 3,
    matchers: [
      { type: 'body', pattern: '"cluster_name"\\s*:' },
      { type: 'body', pattern: '"tagline"\\s*:\\s*"You Know, for Search"' },
      { type: 'body', pattern: '"lucene_version"' },
      { type: 'body', pattern: '"number"\\s*:\\s*"([\\d.]+)"', versionGroup: 1 },
    ],
    matchMode: 'any',
    tags: ['database', 'elasticsearch', 'search'],
  },
  {
    name: 'OpenSearch',
    product: 'OpenSearch',
    category: 'database',
    priority: 3,
    matchers: [
      { type: 'body', pattern: '"distribution"\\s*:\\s*"opensearch"' },
      { type: 'body', pattern: '"tagline"\\s*:\\s*"The OpenSearch Project' },
      { type: 'body', pattern: '"number"\\s*:\\s*"([\\d.]+)".*"distribution"\\s*:\\s*"opensearch"', flags: 'is', versionGroup: 1 },
    ],
    matchMode: 'any',
    tags: ['database', 'opensearch', 'search'],
  },
  {
    name: 'Apache Solr',
    product: 'Solr',
    category: 'database',
    priority: 3,
    matchers: [
      { type: 'title', pattern: 'Solr Admin' },
      { type: 'body', pattern: 'Solr Admin|Apache Solr|solr-core' },
      { type: 'body', pattern: '"lucene"\\s*:\\s*\\{' },
    ],
    matchMode: 'any',
    tags: ['database', 'solr', 'search'],
  },
  {
    name: 'ClickHouse HTTP',
    product: 'ClickHouse',
    category: 'database',
    priority: 3,
    matchers: [
      { type: 'header', field: 'x-clickhouse-server-display-name', pattern: '.+' },
      { type: 'header', field: 'x-clickhouse-query-id', pattern: '.+' },
      { type: 'body', pattern: 'ClickHouse' },
      { type: 'body', pattern: 'Ok\\.\\s*$' },
    ],
    matchMode: 'any',
    tags: ['database', 'clickhouse', 'olap'],
  },
  {
    name: 'Cassandra CQL',
    product: 'Cassandra',
    category: 'database',
    priority: 2,
    matchers: [
      { type: 'banner', pattern: 'Apache Cassandra' },
      { type: 'banner', pattern: 'cassandra' },
    ],
    matchMode: 'any',
    tags: ['database', 'cassandra', 'nosql'],
  },
  {
    name: 'Aerospike',
    product: 'Aerospike',
    category: 'database',
    priority: 2,
    matchers: [
      { type: 'banner', pattern: 'aerospike' },
      { type: 'banner', pattern: 'Aerospike' },
      { type: 'banner', pattern: 'build\\t([\\w.-]+)', versionGroup: 1 },
    ],
    matchMode: 'any',
    tags: ['database', 'aerospike', 'kv'],
  },
  {
    name: 'HBase REST',
    product: 'HBase',
    category: 'database',
    priority: 3,
    matchers: [
      { type: 'body', pattern: 'HBase' },
      { type: 'header', field: 'server', pattern: 'jetty.*HBase' },
    ],
    matchMode: 'any',
    tags: ['database', 'hbase', 'hadoop'],
  },
  {
    name: 'Memcached',
    product: 'Memcached',
    category: 'database',
    priority: 2,
    matchers: [
      { type: 'banner', pattern: 'STAT version ([\\d.]+)', versionGroup: 1 },
      { type: 'banner', pattern: '^VERSION\\s+([\\w.-]+)', versionGroup: 1 },
    ],
    matchMode: 'any',
    tags: ['database', 'memcached', 'kv'],
  },
  {
    name: 'ZooKeeper',
    product: 'ZooKeeper',
    category: 'database',
    priority: 2,
    matchers: [
      { type: 'banner', pattern: 'imok' },
      { type: 'banner', pattern: 'Zookeeper version|ZooKeeper version' },
      { type: 'banner', pattern: 'Mode:\\s*(standalone|leader|follower)' },
    ],
    matchMode: 'any',
    tags: ['database', 'zookeeper', 'coordination'],
  },
  {
    name: 'etcd',
    product: 'etcd',
    category: 'database',
    priority: 3,
    matchers: [
      { type: 'body', pattern: '"etcdserver"\\s*:\\s*"([\\d.]+)"', versionGroup: 1 },
      { type: 'body', pattern: '"etcdcluster"\\s*:' },
      { type: 'body', pattern: 'etcdserver' },
    ],
    matchMode: 'any',
    tags: ['database', 'etcd', 'kv'],
  },
  {
    name: 'Neo4j',
    product: 'Neo4j',
    category: 'database',
    priority: 3,
    matchers: [
      { type: 'body', pattern: 'neo4j_version|Neo4j Browser|neo4j' },
      { type: 'title', pattern: 'Neo4j' },
      { type: 'header', field: 'www-authenticate', pattern: 'Neo4j' },
    ],
    matchMode: 'any',
    tags: ['database', 'neo4j', 'graph'],
  },
  {
    name: 'RabbitMQ Management',
    product: 'RabbitMQ',
    category: 'database',
    priority: 3,
    matchers: [
      { type: 'body', pattern: 'RabbitMQ Management' },
      { type: 'body', pattern: '"rabbitmq_version"\\s*:' },
      { type: 'title', pattern: 'RabbitMQ Management' },
    ],
    matchMode: 'any',
    tags: ['database', 'rabbitmq', 'mq'],
  },
  {
    name: 'Kafka',
    product: 'Kafka',
    category: 'database',
    priority: 2,
    matchers: [
      { type: 'banner', pattern: 'kafka' },
      { type: 'banner', pattern: 'Kafka Metadata' },
      { type: 'body', pattern: 'Kafka' },
    ],
    matchMode: 'any',
    tags: ['database', 'kafka', 'mq'],
  },
  {
    name: 'RocketMQ',
    product: 'RocketMQ',
    category: 'database',
    priority: 2,
    matchers: [
      { type: 'banner', pattern: 'RocketMQ' },
      { type: 'body', pattern: 'RocketMQ|rocketmq-dashboard|rocketmq-console' },
      { type: 'title', pattern: 'RocketMQ' },
    ],
    matchMode: 'any',
    tags: ['database', 'rocketmq', 'mq'],
  },
  {
    name: 'Apache Pulsar',
    product: 'Pulsar',
    category: 'database',
    priority: 2,
    matchers: [
      { type: 'banner', pattern: 'Pulsar' },
      { type: 'body', pattern: 'Apache Pulsar|Pulsar Manager|pulsar-admin' },
      { type: 'title', pattern: 'Pulsar' },
    ],
    matchMode: 'any',
    tags: ['database', 'pulsar', 'mq'],
  },
  {
    name: 'Trino',
    product: 'Trino',
    category: 'database',
    priority: 3,
    matchers: [
      { type: 'header', field: 'x-trino-server', pattern: '([\\d.]+)', versionGroup: 1 },
      { type: 'title', pattern: 'Trino' },
      { type: 'body', pattern: 'Trino UI|Trino Coordinator|x-trino' },
    ],
    matchMode: 'any',
    tags: ['database', 'trino', 'query-engine'],
  },
  {
    name: 'Presto',
    product: 'Presto',
    category: 'database',
    priority: 3,
    matchers: [
      { type: 'header', field: 'x-presto-server', pattern: '([\\d.]+)', versionGroup: 1 },
      { type: 'title', pattern: 'Presto' },
      { type: 'body', pattern: 'Presto UI|Presto Coordinator|x-presto' },
    ],
    matchMode: 'any',
    tags: ['database', 'presto', 'query-engine'],
  },
  {
    name: 'HiveServer2',
    product: 'Hive',
    category: 'database',
    priority: 3,
    matchers: [
      { type: 'banner', pattern: 'HiveServer2|Apache Hive' },
      { type: 'title', pattern: 'HiveServer2|Apache Hive' },
      { type: 'body', pattern: 'HiveServer2|Apache Hive|hive.server2' },
    ],
    matchMode: 'any',
    tags: ['database', 'hive', 'hadoop'],
  },
  {
    name: 'HDFS Web UI',
    product: 'HDFS',
    category: 'database',
    priority: 3,
    matchers: [
      { type: 'title', pattern: 'NameNode|DataNode|HDFS' },
      { type: 'body', pattern: 'Hadoop|NameNode|DataNode|dfshealth\\.html|WebHDFS' },
    ],
    matchMode: 'any',
    tags: ['database', 'hdfs', 'hadoop'],
  },
  {
    name: 'Microsoft SQL Server',
    product: 'MSSQL',
    category: 'database',
    priority: 2,
    matchers: [
      { type: 'banner', pattern: 'SQL Server|MSSQL|TDS' },
    ],
    matchMode: 'any',
    tags: ['database', 'mssql'],
  },
  {
    name: 'Oracle Database',
    product: 'Oracle',
    category: 'database',
    priority: 2,
    matchers: [
      { type: 'banner', pattern: 'Oracle|TNSLSNR|ORA-\\d+' },
    ],
    matchMode: 'any',
    tags: ['database', 'oracle'],
  },
  {
    name: 'CouchDB',
    product: 'CouchDB',
    category: 'database',
    priority: 3,
    matchers: [
      { type: 'body', pattern: '"couchdb"\\s*:\\s*"Welcome"' },
      { type: 'header', field: 'server', pattern: 'CouchDB' },
    ],
    matchMode: 'any',
    tags: ['database', 'couchdb', 'nosql'],
  },
  {
    name: 'InfluxDB',
    product: 'InfluxDB',
    category: 'database',
    priority: 3,
    matchers: [
      { type: 'header', field: 'x-influxdb-version', pattern: '.+' },
      { type: 'header', field: 'x-influxdb-build', pattern: '.+' },
    ],
    matchMode: 'any',
    tags: ['database', 'influxdb', 'tsdb'],
  },
];
