import type { FingerprintRule } from '@sasp/shared';

type Seed = Omit<FingerprintRule, 'id' | 'enabled' | 'source'>;

// 运维管控 / 监控 / 内部平台 — 常见"入口"类资产
export const devopsRules: Seed[] = [
  {
    name: 'Grafana',
    product: 'Grafana',
    category: 'monitoring',
    priority: 3,
    matchers: [
      { type: 'body', pattern: '<title>Grafana' },
      { type: 'body', pattern: '"appSubUrl":"","buildInfo"' },
      { type: 'title', pattern: 'Grafana' },
      { type: 'header', field: 'set-cookie', pattern: 'grafana_session' },
    ],
    matchMode: 'any',
    tags: ['monitoring', 'grafana'],
  },
  {
    name: 'Kibana',
    product: 'Kibana',
    category: 'monitoring',
    priority: 3,
    matchers: [
      { type: 'header', field: 'kbn-name', pattern: '.+' },
      { type: 'header', field: 'kbn-version', pattern: '([\\d.]+)', versionGroup: 1 },
      { type: 'body', pattern: 'kbn-injected-metadata' },
      { type: 'title', pattern: 'Kibana' },
    ],
    matchMode: 'any',
    tags: ['monitoring', 'kibana', 'elk'],
  },
  {
    name: 'PrometheusAlert',
    product: 'PrometheusAlert',
    category: 'monitoring',
    priority: 2,
    matchers: [
      { type: 'title', pattern: 'PrometheusAlert' },
      { type: 'body', pattern: 'PrometheusAlert\\s*\\|\\s*登录控制中心' },
    ],
    matchMode: 'any',
    tags: ['monitoring', 'prometheus-alert', 'alerting'],
  },
  {
    name: 'Prometheus',
    product: 'Prometheus',
    category: 'monitoring',
    priority: 3,
    matchers: [
      { type: 'title', pattern: 'Prometheus Time Series Collection' },
      { type: 'body', pattern: 'Prometheus' },
      { type: 'body', pattern: '<a href="/graph">' },
    ],
    matchMode: 'any',
    tags: ['monitoring', 'prometheus'],
  },
  {
    name: 'Asynqmon',
    product: 'Asynq',
    category: 'monitoring',
    priority: 2,
    matchers: [
      { type: 'title', pattern: 'Asynq\\s*-\\s*Monitoring' },
      { type: 'body', pattern: 'Asynq monitoring web console' },
      { type: 'body', pattern: 'window\\.FLAG_ROOT_PATH=.*?/dashboard' },
    ],
    matchMode: 'any',
    tags: ['monitoring', 'asynq', 'queue'],
  },
  {
    name: 'Jenkins',
    product: 'Jenkins',
    category: 'devops',
    priority: 3,
    matchers: [
      { type: 'header', field: 'x-jenkins', pattern: '([\\d.]+)', versionGroup: 1 },
      { type: 'header', field: 'x-hudson', pattern: '.+' },
      { type: 'title', pattern: 'Jenkins' },
    ],
    matchMode: 'any',
    tags: ['devops', 'jenkins', 'ci'],
  },
  {
    name: 'GitLab',
    product: 'GitLab',
    category: 'devops',
    priority: 3,
    matchers: [
      { type: 'header', field: 'x-gitlab-meta', pattern: '.+' },
      { type: 'header', field: 'set-cookie', pattern: '_gitlab_session' },
      { type: 'title', pattern: 'GitLab' },
    ],
    matchMode: 'any',
    tags: ['devops', 'gitlab', 'git'],
  },
  {
    name: 'Gitea',
    product: 'Gitea',
    category: 'devops',
    priority: 3,
    matchers: [
      { type: 'header', field: 'set-cookie', pattern: 'i_like_gitea' },
      { type: 'body', pattern: 'Powered by Gitea' },
    ],
    matchMode: 'any',
    tags: ['devops', 'gitea', 'git'],
  },
  {
    name: 'Nexus Repository',
    product: 'Nexus',
    category: 'devops',
    priority: 3,
    matchers: [
      { type: 'header', field: 'server', pattern: 'Nexus' },
      { type: 'body', pattern: 'Sonatype Nexus' },
    ],
    matchMode: 'any',
    tags: ['devops', 'nexus', 'repository'],
  },
  {
    name: 'Harbor',
    product: 'Harbor',
    category: 'devops',
    priority: 3,
    matchers: [
      { type: 'header', field: 'set-cookie', pattern: 'harbor' },
      { type: 'title', pattern: 'Harbor' },
    ],
    matchMode: 'any',
    tags: ['devops', 'harbor', 'registry', 'docker'],
  },
  {
    name: 'Portainer',
    product: 'Portainer',
    category: 'devops',
    priority: 3,
    matchers: [
      { type: 'title', pattern: 'Portainer' },
      { type: 'body', pattern: 'portainer' },
    ],
    matchMode: 'any',
    tags: ['devops', 'portainer', 'docker'],
  },
  {
    name: 'Docker API',
    product: 'Docker API',
    category: 'devops',
    priority: 2,
    matchers: [
      { type: 'body', pattern: '"ApiVersion"\\s*:\\s*"' },
      { type: 'body', pattern: '"DockerRootDir"\\s*:' },
      { type: 'body', pattern: 'client version .* is too (new|old)' },
    ],
    matchMode: 'any',
    tags: ['devops', 'docker', 'api'],
  },
  {
    name: 'Kubernetes Dashboard',
    product: 'Kubernetes Dashboard',
    category: 'devops',
    priority: 3,
    matchers: [
      { type: 'title', pattern: 'Kubernetes Dashboard' },
      { type: 'body', pattern: 'kubernetes-dashboard' },
    ],
    matchMode: 'any',
    tags: ['devops', 'kubernetes', 'k8s'],
  },
  {
    name: 'Kubelet',
    product: 'Kubelet',
    category: 'devops',
    priority: 2,
    matchers: [
      { type: 'body', pattern: 'kubelet|/pods|/stats/summary|/metrics/cadvisor' },
      { type: 'header', field: 'www-authenticate', pattern: 'Kubelet' },
    ],
    matchMode: 'any',
    tags: ['devops', 'kubernetes', 'kubelet'],
  },
  {
    name: 'Consul',
    product: 'Consul',
    category: 'devops',
    priority: 3,
    matchers: [
      { type: 'header', field: 'x-consul-index', pattern: '.+' },
      { type: 'title', pattern: 'Consul' },
    ],
    matchMode: 'any',
    tags: ['devops', 'consul', 'hashicorp'],
  },
  {
    name: 'Nacos',
    product: 'Nacos',
    category: 'devops',
    priority: 3,
    matchers: [
      { type: 'body', pattern: 'Nacos' },
      { type: 'title', pattern: 'Nacos' },
    ],
    matchMode: 'any',
    tags: ['devops', 'nacos', 'registry'],
  },
  {
    name: 'Zabbix',
    product: 'Zabbix',
    category: 'monitoring',
    priority: 3,
    matchers: [
      { type: 'header', field: 'set-cookie', pattern: 'zbx_session' },
      { type: 'title', pattern: 'Zabbix' },
    ],
    matchMode: 'any',
    tags: ['monitoring', 'zabbix'],
  },
  {
    name: 'phpMyAdmin',
    product: 'phpMyAdmin',
    category: 'devops',
    priority: 3,
    matchers: [
      { type: 'header', field: 'set-cookie', pattern: 'phpMyAdmin' },
      { type: 'title', pattern: 'phpMyAdmin' },
      { type: 'body', pattern: 'phpMyAdmin' },
    ],
    matchMode: 'any',
    tags: ['devops', 'phpmyadmin', 'database'],
  },
  {
    name: 'Argo CD',
    product: 'Argo CD',
    category: 'devops',
    priority: 2,
    matchers: [
      { type: 'title', pattern: 'Argo CD' },
      { type: 'body', pattern: '<title>Argo CD</title>' },
      { type: 'body', pattern: 'argocd-server|argo-cd' },
    ],
    matchMode: 'any',
    tags: ['devops', 'argocd', 'kubernetes', 'gitops'],
  },
  {
    name: 'Kafka Connect REST',
    product: 'Kafka Connect',
    category: 'devops',
    priority: 2,
    matchers: [
      { type: 'body', pattern: '"kafka_cluster_id"\\s*:' },
      { type: 'body', pattern: '"commit"\\s*:.*"version"\\s*:', flags: 'is' },
      { type: 'body', pattern: '"error_code"\\s*:\\s*404.*"message"\\s*:\\s*"HTTP 404 Not Found"', flags: 'is' },
    ],
    matchMode: 'any',
    tags: ['devops', 'kafka', 'kafka-connect'],
  },
  {
    name: 'FastAPI Docs',
    product: 'FastAPI',
    category: 'framework',
    priority: 2,
    matchers: [
      { type: 'title', pattern: 'FastAPI\\s*-\\s*Swagger UI' },
      { type: 'title', pattern: 'FastAPI\\s*-\\s*ReDoc' },
      { type: 'body', pattern: '<title>FastAPI\\s*-\\s*(Swagger UI|ReDoc)</title>' },
    ],
    matchMode: 'any',
    tags: ['framework', 'fastapi', 'swagger', 'api'],
  },
  {
    name: 'Swagger UI',
    product: 'Swagger UI',
    category: 'framework',
    priority: 3,
    matchers: [
      { type: 'body', pattern: 'swagger-ui' },
      { type: 'title', pattern: 'Swagger UI' },
    ],
    matchMode: 'any',
    tags: ['framework', 'swagger', 'api'],
  },
  {
    name: 'Apache Flink Dashboard',
    product: 'Apache Flink',
    category: 'devops',
    priority: 2,
    matchers: [
      { type: 'title', pattern: 'Apache Flink Web Dashboard' },
      { type: 'body', pattern: 'Apache Flink Web Dashboard|flink-runtime-web' },
    ],
    matchMode: 'any',
    tags: ['devops', 'flink', 'bigdata'],
  },
  {
    name: 'LiteLLM Proxy',
    product: 'LiteLLM',
    category: 'devops',
    priority: 2,
    matchers: [
      { type: 'body', pattern: '"title"\\s*:\\s*"LiteLLM API"' },
      { type: 'body', pattern: 'LiteLLM Admin Panel' },
      { type: 'body', pattern: 'Proxy Server to call 100\\+ LLMs' },
    ],
    matchMode: 'any',
    tags: ['devops', 'ai', 'llm', 'proxy'],
  },
  {
    name: 'Certimate',
    product: 'Certimate',
    category: 'devops',
    priority: 2,
    matchers: [
      { type: 'title', pattern: 'Certimate' },
      { type: 'body', pattern: 'Your Trusted SSL Automation Partner' },
    ],
    matchMode: 'any',
    tags: ['devops', 'certificate', 'ssl'],
  },
  {
    name: 'Spring Boot Actuator',
    product: 'Spring Boot',
    category: 'framework',
    priority: 3,
    matchers: [
      { type: 'body', pattern: '\\{"_links":\\{"self":\\{"href":"[^"]*actuator' },
      { type: 'body', pattern: 'Whitelabel Error Page' },
    ],
    matchMode: 'any',
    tags: ['framework', 'spring', 'java'],
  },
];
