import type { FingerprintRule } from '@sasp/shared';

type Seed = Omit<FingerprintRule, 'id' | 'enabled' | 'source'>;

export const middlewareRules: Seed[] = [
  {
    name: 'Nginx',
    product: 'Nginx',
    category: 'webserver',
    priority: 3,
    matchers: [
      { type: 'header', field: 'server', pattern: '^nginx(?:/([\\d.]+))?', versionGroup: 1 },
      { type: 'title', pattern: 'Welcome to nginx!' },
      { type: 'body', pattern: '<center>nginx(?:/([\\d.]+))?</center>', versionGroup: 1 },
    ],
    matchMode: 'any',
    tags: ['webserver', 'nginx'],
  },
  {
    name: 'OpenResty',
    product: 'OpenResty',
    category: 'webserver',
    priority: 3,
    matchers: [
      { type: 'header', field: 'server', pattern: 'openresty(?:/([\\d.]+))?', versionGroup: 1 },
      { type: 'title', pattern: 'Welcome to OpenResty!' },
      { type: 'body', pattern: '<center>openresty(?:/([\\d.]+))?</center>', versionGroup: 1 },
    ],
    matchMode: 'any',
    tags: ['webserver', 'openresty', 'nginx'],
  },
  {
    name: 'Apache httpd',
    product: 'Apache',
    category: 'webserver',
    priority: 3,
    matchers: [
      { type: 'header', field: 'server', pattern: '^Apache(?:/([\\d.]+))?', versionGroup: 1 },
    ],
    tags: ['webserver', 'apache'],
  },
  {
    name: 'Caddy',
    product: 'Caddy',
    category: 'webserver',
    priority: 3,
    matchers: [
      { type: 'header', field: 'server', pattern: 'Caddy' },
    ],
    tags: ['webserver', 'caddy'],
  },
  {
    name: 'IIS',
    product: 'Microsoft-IIS',
    category: 'webserver',
    priority: 3,
    matchers: [
      { type: 'header', field: 'server', pattern: 'Microsoft-IIS/([\\d.]+)', versionGroup: 1 },
    ],
    tags: ['webserver', 'iis'],
  },
  {
    name: 'Python SimpleHTTPServer',
    product: 'Python SimpleHTTPServer',
    category: 'webserver',
    priority: 3,
    matchers: [
      { type: 'header', field: 'server', pattern: 'SimpleHTTP/([\\d.]+) Python/([\\d.]+)' },
      { type: 'title', pattern: 'Directory listing for /' },
    ],
    matchMode: 'any',
    tags: ['webserver', 'python', 'directory-listing'],
  },
  {
    name: 'Tomcat',
    product: 'Tomcat',
    category: 'middleware',
    priority: 3,
    matchers: [
      { type: 'header', field: 'server', pattern: 'Apache-Coyote' },
      { type: 'body', pattern: 'Apache Tomcat(?:/([\\d.]+))?', versionGroup: 1 },
      { type: 'title', pattern: 'Apache Tomcat' },
    ],
    matchMode: 'any',
    tags: ['middleware', 'tomcat', 'java'],
  },
  {
    name: 'Spring Security Login',
    product: 'Spring Security',
    category: 'framework',
    priority: 3,
    matchers: [
      { type: 'title', pattern: '^Please sign in$' },
      { type: 'body', pattern: 'Username\\s+Password\\s+Sign in' },
      { type: 'body', pattern: '"timestamp"\\s*:.*"status"\\s*:\\s*401.*"error"\\s*:\\s*"Unauthorized"', flags: 'is' },
    ],
    matchMode: 'any',
    tags: ['framework', 'spring', 'java', 'login'],
  },
  {
    name: 'Jetty',
    product: 'Jetty',
    category: 'middleware',
    priority: 3,
    matchers: [
      { type: 'header', field: 'server', pattern: 'Jetty(?:\\(([\\d.]+))?', versionGroup: 1 },
    ],
    tags: ['middleware', 'jetty', 'java'],
  },
  {
    name: 'WebLogic',
    product: 'WebLogic',
    category: 'middleware',
    priority: 3,
    matchers: [
      { type: 'body', pattern: 'Oracle WebLogic' },
      { type: 'title', pattern: 'Oracle WebLogic' },
      { type: 'title', pattern: 'Welcome to WebLogic' },
    ],
    matchMode: 'any',
    tags: ['middleware', 'weblogic', 'java', 'oracle'],
  },
  {
    name: 'JBoss',
    product: 'JBoss',
    category: 'middleware',
    priority: 3,
    matchers: [
      { type: 'header', field: 'x-powered-by', pattern: 'JBoss' },
      { type: 'title', pattern: 'JBoss' },
    ],
    matchMode: 'any',
    tags: ['middleware', 'jboss', 'java'],
  },
  {
    name: 'WildFly',
    product: 'WildFly',
    category: 'middleware',
    priority: 3,
    matchers: [
      { type: 'header', field: 'x-powered-by', pattern: 'WildFly' },
    ],
    tags: ['middleware', 'wildfly', 'java'],
  },
  {
    name: 'SSH Server',
    product: 'SSH',
    category: 'middleware',
    priority: 0,
    matchers: [
      { type: 'banner', pattern: '^SSH-2\\.0-(\\S+)', versionGroup: 1 },
      { type: 'banner', pattern: '^SSH-' },
    ],
    matchMode: 'any',
    tags: ['ssh'],
  },
  {
    name: 'FTP Server',
    product: 'FTP',
    category: 'middleware',
    priority: 0,
    matchers: [
      { type: 'banner', pattern: '^220.*FTP' },
      { type: 'banner', pattern: '^220.*vsftpd ([\\d.]+)', versionGroup: 1 },
      { type: 'banner', pattern: '^220.*ProFTPD' },
    ],
    matchMode: 'any',
    tags: ['ftp'],
  },
  {
    name: 'SMTP Server',
    product: 'SMTP',
    category: 'middleware',
    priority: 1,
    matchers: [
      { type: 'banner', pattern: '^220[ -].*(?:ESMTP|SMTP|Postfix|Exim|Sendmail|Microsoft ESMTP|Exchange)' },
      { type: 'banner', pattern: 'Postfix|Exim|Sendmail|Microsoft ESMTP|Exchange Server' },
    ],
    matchMode: 'any',
    tags: ['mail', 'smtp'],
  },
  {
    name: 'POP3 Server',
    product: 'POP3',
    category: 'middleware',
    priority: 1,
    matchers: [
      { type: 'banner', pattern: '^\\+OK.*(?:POP3|Dovecot|Cyrus)' },
      { type: 'banner', pattern: 'Dovecot ready|Cyrus POP3' },
    ],
    matchMode: 'any',
    tags: ['mail', 'pop3'],
  },
  {
    name: 'IMAP Server',
    product: 'IMAP',
    category: 'middleware',
    priority: 1,
    matchers: [
      { type: 'banner', pattern: '^\\* OK.*(?:IMAP|Dovecot|Cyrus)' },
      { type: 'banner', pattern: 'IMAP4rev1|Dovecot ready|Cyrus IMAP' },
    ],
    matchMode: 'any',
    tags: ['mail', 'imap'],
  },
  {
    name: 'VNC Server',
    product: 'VNC',
    category: 'middleware',
    priority: 1,
    matchers: [
      { type: 'banner', pattern: '^RFB\\s+([\\d.]+)', versionGroup: 1 },
    ],
    tags: ['remote-access', 'vnc'],
  },
  {
    name: 'Rsync Daemon',
    product: 'Rsync',
    category: 'middleware',
    priority: 1,
    matchers: [
      { type: 'banner', pattern: '^@RSYNCD:\\s*([\\d.]+)', versionGroup: 1 },
    ],
    tags: ['file-transfer', 'rsync'],
  },
  {
    name: 'ActiveMQ',
    product: 'ActiveMQ',
    category: 'middleware',
    priority: 2,
    matchers: [
      { type: 'title', pattern: 'ActiveMQ' },
      { type: 'body', pattern: 'Apache ActiveMQ|activemq' },
    ],
    matchMode: 'any',
    tags: ['middleware', 'mq', 'activemq'],
  },
  {
    name: 'RabbitMQ Management',
    product: 'RabbitMQ',
    category: 'middleware',
    priority: 3,
    matchers: [
      { type: 'header', field: 'server', pattern: 'Cowboy' },
      { type: 'body', pattern: 'RabbitMQ Management' },
      { type: 'title', pattern: 'RabbitMQ Management' },
    ],
    matchMode: 'any',
    tags: ['middleware', 'mq', 'rabbitmq'],
  },
  {
    name: 'Kafka',
    product: 'Kafka',
    category: 'middleware',
    priority: 2,
    matchers: [
      { type: 'banner', pattern: 'kafka' },
    ],
    tags: ['middleware', 'mq', 'kafka'],
  },
  {
    name: 'Zookeeper',
    product: 'Zookeeper',
    category: 'middleware',
    priority: 2,
    matchers: [
      { type: 'banner', pattern: 'zookeeper' },
      { type: 'banner', pattern: 'imok' },
    ],
    matchMode: 'any',
    tags: ['middleware', 'zookeeper'],
  },
];
