import type { FingerprintRule } from '@sasp/shared';

type Seed = Omit<FingerprintRule, 'id' | 'enabled' | 'source'>;

// Web 应用 / CMS / 国内后台框架
export const webappRules: Seed[] = [
  // ─── 国内主流后台 / OA / ERP ────────────────────────
  {
    name: 'ActionSoft AWS PaaS',
    product: 'ActionSoft',
    category: 'framework',
    priority: 2,
    matchers: [
      { type: 'body', pattern: 'com\\.actionsoft\\.' },
      { type: 'body', pattern: 'ActionSoft|AWS PaaS|actionsoft' },
      { type: 'title', pattern: '协同办公平台' },
    ],
    matchMode: 'any',
    tags: ['framework', 'actionsoft', 'oa', 'cn'],
  },
  {
    name: 'RuoYi 后台',
    product: 'RuoYi',
    category: 'framework',
    priority: 3,
    matchers: [
      // 典型响应:{"msg":"请求访问:xxx,认证失败","code":401}
      { type: 'body', pattern: '请通过前端地址访问' },
      { type: 'body', pattern: '欢迎使用RuoYi' },
      { type: 'body', pattern: 'RuoYi' },
      { type: 'body', pattern: '认证失败，无法访问系统资源' },
      { type: 'title', pattern: 'RuoYi|若依' },
      { type: 'header', field: 'set-cookie', pattern: 'Admin-Token|satoken' },
    ],
    matchMode: 'any',
    tags: ['framework', 'ruoyi', 'cn', 'admin'],
  },
  {
    name: 'Jeecg Boot',
    product: 'JeecgBoot',
    category: 'framework',
    priority: 3,
    matchers: [
      { type: 'body', pattern: 'jeecg' },
      { type: 'body', pattern: 'JeecgBoot' },
      { type: 'title', pattern: 'Jeecg' },
      { type: 'header', field: 'access-control-allow-headers', pattern: 'X-Access-Token' },
    ],
    matchMode: 'any',
    tags: ['framework', 'jeecg', 'cn', 'admin'],
  },
  {
    name: '致远 OA',
    product: 'Seeyon OA',
    category: 'cms',
    priority: 3,
    matchers: [
      { type: 'body', pattern: '致远互联|Seeyon|seeyon' },
      { type: 'title', pattern: '致远|Seeyon' },
      { type: 'body', pattern: '/seeyon/' },
    ],
    matchMode: 'any',
    tags: ['oa', 'seeyon', 'cn'],
  },
  {
    name: '通达 OA',
    product: 'Tongda OA',
    category: 'cms',
    priority: 3,
    matchers: [
      { type: 'body', pattern: 'TDOA|tongda|通达' },
      { type: 'header', field: 'set-cookie', pattern: 'PHPSESSID=.*TDOA' },
      { type: 'title', pattern: '通达OA|Office Anywhere' },
    ],
    matchMode: 'any',
    tags: ['oa', 'tongda', 'cn'],
  },
  {
    name: '泛微 OA',
    product: 'Weaver E-Office',
    category: 'cms',
    priority: 3,
    matchers: [
      { type: 'body', pattern: '泛微|weaver|e-office|ecology' },
      { type: 'title', pattern: '泛微|E-Office|Ecology' },
      { type: 'header', field: 'set-cookie', pattern: 'ecology_JSessionId' },
    ],
    matchMode: 'any',
    tags: ['oa', 'weaver', 'cn'],
  },
  {
    name: '蓝凌 OA',
    product: 'Landray OA',
    category: 'cms',
    priority: 3,
    matchers: [
      { type: 'body', pattern: '蓝凌|landray' },
      { type: 'body', pattern: 'sys-search-main|landrayOA' },
      { type: 'title', pattern: '蓝凌|Landray' },
    ],
    matchMode: 'any',
    tags: ['oa', 'landray', 'cn'],
  },
  {
    name: '禅道',
    product: 'ZenTao',
    category: 'devops',
    priority: 3,
    matchers: [
      { type: 'body', pattern: 'ZenTao|禅道' },
      { type: 'title', pattern: '禅道|ZenTao' },
      { type: 'header', field: 'set-cookie', pattern: 'zentaosid' },
    ],
    matchMode: 'any',
    tags: ['project-mgmt', 'zentao', 'cn'],
  },
  {
    name: '用友 NC/U8',
    product: 'YonYou',
    category: 'cms',
    priority: 3,
    matchers: [
      { type: 'body', pattern: '用友|yonyou|UFIDA' },
      { type: 'title', pattern: '用友|YonYou' },
    ],
    matchMode: 'any',
    tags: ['erp', 'yonyou', 'cn'],
  },
  {
    name: '金蝶 K3 Cloud',
    product: 'Kingdee',
    category: 'cms',
    priority: 3,
    matchers: [
      { type: 'body', pattern: '金蝶|Kingdee|K3Cloud' },
      { type: 'title', pattern: '金蝶|Kingdee' },
    ],
    matchMode: 'any',
    tags: ['erp', 'kingdee', 'cn'],
  },
  {
    name: 'JumpServer',
    product: 'JumpServer',
    category: 'devops',
    priority: 3,
    matchers: [
      { type: 'body', pattern: 'JumpServer' },
      { type: 'title', pattern: 'JumpServer' },
      { type: 'header', field: 'x-jms-org', pattern: '.+' },
    ],
    matchMode: 'any',
    tags: ['devops', 'jumpserver', 'bastion', 'cn'],
  },
  {
    name: 'Pixel Track',
    product: 'Pixel Track',
    category: 'other',
    priority: 2,
    matchers: [
      { type: 'title', pattern: 'EndPoint List' },
      { type: 'body', pattern: 'EndPoint List' },
      { type: 'body', pattern: 'EndPoint List\\s+Pixel Track' },
    ],
    matchMode: 'any',
    tags: ['business', 'tracking', 'pixel'],
  },
  {
    name: 'OpenSong',
    product: 'OpenSong',
    category: 'other',
    priority: 2,
    matchers: [
      { type: 'title', pattern: 'OpenSong' },
      { type: 'body', pattern: 'AI Music Generator|My Music Library \\| OpenSong' },
    ],
    matchMode: 'any',
    tags: ['business', 'ai', 'music'],
  },
  {
    name: 'Next.js App',
    product: 'Next.js',
    category: 'framework',
    priority: 4,
    matchers: [
      { type: 'header', field: 'x-powered-by', pattern: 'Next\\.js' },
      { type: 'body', pattern: '/_next/static/' },
    ],
    matchMode: 'any',
    tags: ['framework', 'nextjs', 'react'],
  },
  {
    name: 'CentOS Default Page',
    product: 'CentOS Default Page',
    category: 'other',
    priority: 3,
    matchers: [
      { type: 'title', pattern: 'Welcome to CentOS' },
      { type: 'body', pattern: 'The Community ENTerprise Operating System' },
    ],
    matchMode: 'any',
    tags: ['default-page', 'centos'],
  },
  // ─── 国际主流产品 ────────────────────────────────
  {
    name: 'Atlassian Jira',
    product: 'Jira',
    category: 'devops',
    priority: 3,
    matchers: [
      { type: 'header', field: 'x-ausername', pattern: '.+' },
      { type: 'body', pattern: 'jira-issue-create-launcher|jira\\.webresources' },
      { type: 'title', pattern: 'Jira|System Dashboard' },
    ],
    matchMode: 'any',
    tags: ['devops', 'jira', 'atlassian'],
  },
  {
    name: 'Atlassian Confluence',
    product: 'Confluence',
    category: 'devops',
    priority: 3,
    matchers: [
      { type: 'body', pattern: 'Confluence|atlassian-confluence' },
      { type: 'title', pattern: 'Confluence' },
      { type: 'header', field: 'x-confluence-request-time', pattern: '.+' },
    ],
    matchMode: 'any',
    tags: ['devops', 'confluence', 'atlassian'],
  },
  {
    name: 'Bitbucket',
    product: 'Bitbucket',
    category: 'devops',
    priority: 3,
    matchers: [
      { type: 'header', field: 'x-arequestid', pattern: '.+' },
      { type: 'body', pattern: 'bitbucket' },
      { type: 'title', pattern: 'Bitbucket' },
    ],
    matchMode: 'any',
    tags: ['devops', 'bitbucket', 'git'],
  },
  {
    name: 'SonarQube',
    product: 'SonarQube',
    category: 'devops',
    priority: 3,
    matchers: [
      { type: 'body', pattern: 'SonarQube' },
      { type: 'title', pattern: 'SonarQube' },
      { type: 'header', field: 'set-cookie', pattern: 'XSRF-TOKEN' },
    ],
    matchMode: 'any',
    tags: ['devops', 'sonarqube', 'code-quality'],
  },
  {
    name: 'MinIO',
    product: 'MinIO',
    category: 'middleware',
    priority: 3,
    matchers: [
      { type: 'header', field: 'server', pattern: 'MinIO' },
      { type: 'body', pattern: 'minio' },
    ],
    matchMode: 'any',
    tags: ['middleware', 'minio', 's3'],
  },
  {
    name: 'Apache Airflow',
    product: 'Airflow',
    category: 'devops',
    priority: 3,
    matchers: [
      { type: 'title', pattern: 'Airflow' },
      { type: 'body', pattern: 'airflow' },
    ],
    matchMode: 'any',
    tags: ['devops', 'airflow', 'workflow'],
  },
  {
    name: 'Apache Superset',
    product: 'Superset',
    category: 'devops',
    priority: 3,
    matchers: [
      { type: 'title', pattern: 'Superset' },
      { type: 'body', pattern: 'superset' },
    ],
    matchMode: 'any',
    tags: ['devops', 'superset', 'bi'],
  },
  {
    name: 'Metabase',
    product: 'Metabase',
    category: 'devops',
    priority: 3,
    matchers: [
      { type: 'title', pattern: 'Metabase' },
      { type: 'body', pattern: 'metabase' },
      { type: 'header', field: 'x-metabase-version', pattern: '.+' },
    ],
    matchMode: 'any',
    tags: ['devops', 'metabase', 'bi'],
  },
  {
    name: 'Apollo Config',
    product: 'Apollo',
    category: 'middleware',
    priority: 3,
    matchers: [
      { type: 'body', pattern: 'apollo-portal|ctrip\\.framework\\.apollo' },
      { type: 'title', pattern: 'Apollo' },
    ],
    matchMode: 'any',
    tags: ['middleware', 'apollo', 'config', 'ctrip'],
  },
  {
    name: 'Seata',
    product: 'Seata',
    category: 'middleware',
    priority: 3,
    matchers: [
      { type: 'body', pattern: 'Seata|seata' },
      { type: 'title', pattern: 'Seata' },
    ],
    matchMode: 'any',
    tags: ['middleware', 'seata', 'distributed-tx'],
  },
  // ─── CMS / 博客 ──────────────────────────────────
  {
    name: 'WordPress',
    product: 'WordPress',
    category: 'cms',
    priority: 3,
    matchers: [
      { type: 'body', pattern: 'wp-content|wp-includes|wordpress' },
      { type: 'header', field: 'x-powered-by', pattern: 'WordPress' },
      { type: 'title', pattern: 'WordPress' },
    ],
    matchMode: 'any',
    tags: ['cms', 'wordpress', 'blog'],
  },
  {
    name: 'Joomla',
    product: 'Joomla',
    category: 'cms',
    priority: 3,
    matchers: [
      { type: 'body', pattern: 'Joomla!|joomla' },
      { type: 'header', field: 'x-content-encoded-by', pattern: 'Joomla' },
    ],
    matchMode: 'any',
    tags: ['cms', 'joomla'],
  },
  {
    name: 'Drupal',
    product: 'Drupal',
    category: 'cms',
    priority: 3,
    matchers: [
      { type: 'header', field: 'x-generator', pattern: 'Drupal' },
      { type: 'body', pattern: 'drupal.js' },
    ],
    matchMode: 'any',
    tags: ['cms', 'drupal'],
  },
  {
    name: 'Thinkphp',
    product: 'ThinkPHP',
    category: 'framework',
    priority: 3,
    matchers: [
      { type: 'header', field: 'x-powered-by', pattern: 'ThinkPHP' },
      { type: 'body', pattern: 'ThinkPHP' },
    ],
    matchMode: 'any',
    tags: ['framework', 'thinkphp', 'php', 'cn'],
  },
  // ─── 安全类 / 其他 ──────────────────────────────
  {
    name: 'Shiro',
    product: 'Apache Shiro',
    category: 'framework',
    priority: 3,
    matchers: [
      { type: 'header', field: 'set-cookie', pattern: 'rememberMe=deleteMe' },
      { type: 'header', field: 'set-cookie', pattern: 'JSESSIONID.*rememberMe' },
    ],
    matchMode: 'any',
    tags: ['framework', 'shiro', 'java', 'security'],
  },
  {
    name: 'Struts2',
    product: 'Apache Struts2',
    category: 'framework',
    priority: 3,
    matchers: [
      { type: 'body', pattern: '\\.action\\b' },
      { type: 'body', pattern: 'struts' },
    ],
    matchMode: 'any',
    tags: ['framework', 'struts2', 'java'],
  },
  {
    name: 'Druid 监控',
    product: 'Druid Monitor',
    category: 'monitoring',
    priority: 3,
    matchers: [
      { type: 'body', pattern: 'druid\\.index' },
      { type: 'title', pattern: 'Druid Stat' },
    ],
    matchMode: 'any',
    tags: ['monitoring', 'druid', 'cn'],
  },
];
